# Introducción a NumPy

## ¿Qué es NumPy?

### Palabras Clave

* Paquete
* Matriz multidimensional
* Operaciones rápidas entre matrices
* Objeto ndarray
* Datos homogéneos
* Ejecución de código compilado.

Si nos dirigimos a la documentación oficial de [Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html), podemos decir, en resumen, que es una herramienta útil cuando deseamos realizar operaciones con matrices. Su potencial se muestra al trabajar con matrices de tamaños cada vez más grandes, ya que ejecuta código compilado para realizar las operaciones sin la necesidad de salir de Python.

Es importante destacar que los objetos ndarray deben ser de **datos homogéneos**, mencionándolo para evitar errores de ejecución.

## Diferencias entre el úso de NumPy y las secuencias estándar de Python

|Numpy|Python|
|:--------------------------------------:|:-------------------------:|
|Tamaño fijo en el momento de su creación|Pueden crecer dinámicamente|
|Los elementos deben ser homogéneos|Permite multples datos|
|Facilidad en operaciones matemáticas avanzadas y procesamiento de grandes conjuntos de datos|Requiere implementar las operaciones además de la reducción en el rendimiento|
|Compatibilidad con la mayoría del software científico/matemático basado en Python| **Saber cómo usar los tipos de secuencia integrados de Python es insuficiente**|

> Cambiar el tamaño de un *ndarray* creará una nueva matrz y eliminará el original.

> Es posible crear una matriz de objetos en NumPy permitiendo una mayor flexibilidad. Con la consecuencia de perder rendimiento y la capacidad de aprovechar las implementaciones más eficientes que ofrece el paquete.

> NumPy nos ofrece lo mejor de ambos mundos. Se ejecuta a velocidades cercanas a C, pero con la simplicidad del código que esperamos de algo basado en Python.

## ¿Por qué utilizar NumPy?

Pienso que la principal razón para utilizar NumPy es por su escalabilidad a paquetes basados en Python. Si deseamos utilizar Python como lenguaje de programación enfocado en aplicaciones cientificas de cualquier área NumPy es el estandar, tal es así que en la misma documentación refieren que la mayoria de las paqueterias que se implementan para Python requieren como base un arreglo de Numpy. El punto anterior es el fundamento de la necesidad de aprender a utilizarlo, como segundo punto esta el tiempo. Si nos enfocamos en el análisis de datos, encontraremos con frecuencia conjuntos de datos que superan el millon de datos, por ello es necesario tener una forma eficiente de preparar, procesar y analizar nuestros datos sin tener que sacrificar la facilidad en la codificación, esto es algo que logra el paquete Numpy gracias a las siguientes caracteristicas:

* Vectorización: Permite realizar operaciones en arreglos completos en lugar de iterar sobre elementos individualmente.
* Operaciones en C optimizadas: La implementación de las operaciones que realiza se implementan en C, provocando que se manipulen los datos a un nivel de abstracción más bajo.
* Radiodifusión: Permite realizar operaciones entre arreglos de diferentes formas y tamaños de manera automática y eficiente.

## ¿Cómo empezar a utilizar NumPy?

Lo primero que se debe hacer para utilizar NumPy es instalar la libreria utilizando:

```
pip install numpy

```
Después es necesario importar la biblioteca en nuestro script

In [1]:
# Importación de numpy con alias
import numpy as np

Si la estructura básica para utilizar NumPy es un array entonces debemos saber como crearlos o inicializarlos, antes de poder pensar en operarlos.

### Atributos básicos de la clase ndarray

- `ndarray.ndim`: El número de ejes (dimensiones) del array
- `ndarray.shape`: Es una tupla de números enteros que indica la longitud  de cada dimensión.*(filas, columnas)*
- `ndarray.size`: El número total de elementos del array, es igual a multiplicar los elementos de la tupla devuelta por `shape`.
- `ndarray.dtype`: Devuelve una descripción del tipo de elementos que existen dentro del array. NumPy proporciona algunos tipos adicionales, por ejemplo, `numpy.int32`, `numpy.int16` o `numpy.float64`.

### Creación de un array
#### Desde una lista de Python

In [2]:
lista_01 = [1, 2, 56, 878, 14, 45, 19, 21]
a = np.array(lista_01)
print(a)

[  1   2  56 878  14  45  19  21]


In [3]:
# Longitud de cada dimensión del array a
a.shape

(8,)

> **Nota** Observa que si el array es de una sola dimensión el atributo shape devuelve la tupla *(columnas,)* esta es una convención y lo que indica es que tenemos un array de *1 fila y 8 columnas*.

In [4]:
lista_02 = [[10,155,45],[21,178,75]]
b = np.array(lista_02)
b

array([[ 10, 155,  45],
       [ 21, 178,  75]])

In [5]:
# Longitud de cada dimensión del array b
b.shape

(2, 3)

Existen situaciones en donde necesitamos inicializar un array con valores que desconocemos y NumPy ofrece funciones para crear matrices con *contenido de marcador de posición inicial*.

#### Utilizando una función de NumPy

##### Matriz con ceros

In [6]:
c = np.zeros((5,3)) # Matriz de 5x3 rellena de zeros
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Número de dimensiones de la matriz
c.ndim

2

In [8]:
# Longitud de cada dimensión
c.shape

(5, 3)

In [9]:
# Número de elementos de la matriz
c.size

15

In [10]:
# Tipo de matriz
c.dtype

dtype('float64')

c es una matriz con:
- Dos ejes (**axis**) es decir, dos dimensiones (**rank**).
- Longitud de 5 filas y 3 columnas (**shape**)
- Un tamaño (**size**) de 15.
- Tipo de elemento `float64`

##### Matriz con unos

In [11]:
# Array cuyos valores son todos 1
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

##### Matriz cuyos valores son todos el valor especificado como segundo parámetro

In [12]:
np.full((2, 3, 4), 7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

##### Matriz generada con empty

El resultado no es predecible, rellena las dimensiones que se especifican con valores existentes en la memoria al momento de ejecución

In [13]:
np.empty((3,7,4))

array([[[4.04738577e-320, 2.68771711e-321, 0.00000000e+000,
         2.56806706e-316],
        [4.94065646e-324, 2.56806785e-316, 2.56808920e-316,
         1.18575755e-322],
        [6.93704893e-310, 4.24399158e-314, 5.81021200e-321,
         4.94065646e-324],
        [4.24399158e-314, 1.03753786e-322, 2.56806825e-316,
         6.93705019e-310],
        [6.93701644e-310, 4.94065646e-324, 1.69759663e-313,
         4.94065646e-324],
        [2.56807378e-316, 2.56808327e-316, 1.48219694e-323,
         2.56807497e-316],
        [2.56807615e-316, 2.56807852e-316, 2.56808090e-316,
         9.88131292e-323]],

       [[6.93705076e-310, 0.00000000e+000, 4.94065646e-324,
         2.12199579e-313],
        [2.33419537e-313, 9.88131292e-323, 6.93705076e-310,
         0.00000000e+000],
        [5.58788245e-321, 2.54639495e-313, 2.75859453e-313,
         9.88131292e-323],
        [6.93705076e-310, 0.00000000e+000, 5.43472210e-323,
         2.97079411e-313],
        [3.18299369e-313, 9.88131292e-323

#### Creación de array utilizando una función basada en rangos

##### Utilizando secuencias (arrange)
Cuando nos referimos a secuencias es definir un mínimo, un máximo y un salto entre cada valor sin incluir el valor máximo. `[mínimo, máximo)`

In [14]:
# (minimo, maximo, salto)
np.arange(1,10.5,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

##### Creando separaciones uniformes (linspace)
El siguiente código crea un array desde el 0.1 hasta el 1 con 10 elementos separados uniformemente.

A diferencia de la función anterior, con esta, podemos determinar el número de elementos que queremos que tenga nuestro array de forma más intuitiva.

In [15]:
# (minimo,maximo, número de elementos del array)
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### Creación de array con valores aleatorios (random.rand)
Esta función devuelve valores aleatorios entre 0 y 1

In [16]:
np.random.rand(7,3)

array([[0.65768905, 0.96291442, 0.96688592],
       [0.87358515, 0.73611102, 0.55674651],
       [0.3061494 , 0.12350835, 0.89532284],
       [0.83696749, 0.24846473, 0.78080967],
       [0.27242224, 0.24311382, 0.35494843],
       [0.43346604, 0.07774103, 0.73660568],
       [0.23593348, 0.0034342 , 0.5603241 ]])

#### Creación de array con valores aleatorios siguiendo una distribución normal (random.randn)


In [17]:
np.random.randn(7,4)

array([[ 0.6410787 ,  0.68957051,  0.59897611, -0.11566218],
       [-0.29080831, -0.72898658, -0.75485236,  0.43483924],
       [-1.2512188 , -1.06017064,  0.47319132, -0.8448604 ],
       [ 0.56395502, -0.52186408,  0.39911225, -1.07608577],
       [ 2.15347445, -0.3880962 ,  0.84035677,  0.39759408],
       [ 0.93990232,  0.60558819,  1.70572191,  1.11331004],
       [ 0.56748424,  0.57448037, -0.60992119, -0.58933712]])

### Acceso a los elementos de un array
Definimos un array

#### Unidimensional

In [18]:
array_01 = np.random.rand(6)
print(array_01)
print(f'Dimensiones {array_01.ndim}')
print(f'Longitud de sus dimensiones {array_01.shape}')
print(f'Tipo de datos {array_01.dtype}')

[0.08005271 0.33262315 0.00248996 0.70410642 0.62841394 0.19985071]
Dimensiones 1
Longitud de sus dimensiones (6,)
Tipo de datos float64


In [19]:
# Acceso al elemento 1
array_01[1]

0.33262315161883405

In [20]:
# Acceso a un conjunto de elementos, desde el 2 al 5
array_01[2:5]

array([0.00248996, 0.70410642, 0.62841394])

In [21]:
# Acceso a elementos salteados definiendo el salto
array_01[0::3] # Muestra los elementos 0 y 4

array([0.08005271, 0.70410642])

#### Multidimensional

In [22]:
array_02 = np.array([[2,4,6,8],[10,12,14,16]])
print(array_02)
print(f'Dimensiones {array_02.ndim}')
print(f'Longitud de sus dimensiones {array_02.shape}')
print(f'Tipo de datos {array_02.dtype}')

[[ 2  4  6  8]
 [10 12 14 16]]
Dimensiones 2
Longitud de sus dimensiones (2, 4)
Tipo de datos int64


In [23]:
# Acceso al elemento 5 del array
array_02[1,0]

10

In [24]:
# Acceso a la primera fila del array
array_02[0, :]

array([2, 4, 6, 8])

In [25]:
# Acceso a la segunda fila del array
array_02[1, :]

array([10, 12, 14, 16])

In [26]:
# Acceso al segundo elemento de las dos primeras filas del array
array_02[:, 1]

array([ 4, 12])

### Modificar un Array

Para poder trabajar con NumPy, es necesario saber cómo podemos modificar un array. Un array es mutable, lo que significa que podemos modificarlo en tiempo de ejecución. Para entender cómo modificar un array, mostraremos una serie de ejemplos. En síntesis, cuando hablamos de modificar un array, nos referimos a cambiar sus dimensiones o su contenido, con todos los pormenores que estas acciones puedan tener.

In [43]:
# Array unidimensional
array_uni = np.arange(24) # Crea un vector desde 0 hasta 24
array_uni

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### Modificar contenido y dimensiones

Anteriormente, al hablar de las dimensiones de un array, vimos que hacíamos referencia al atributo 'shape'. Para modificar las dimensiones de un array, tenemos que aplicar este método sobre el vector que queremos modificar y asignarle el nuevo valor que deseamos.

In [44]:
array_uni.shape = (6, 4)
array_uni

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

La ejecución anterior devuelve un array que apunta a los mismos datos de array_uni original. Para ver cuál es la naturaleza de asignar un array a uno nuevo y los efectos que tiene modificar cualquiera de los arrays, veamos los siguientes ejemplos:
1. Generamos un array a partir de otro previamente creado pero con sus dimensiones modificadas. El método `reshape` nos permite modificar las dimensiones de un array directamente, sin necesidad de realizar una asignación como sucedia con `shape`.

In [45]:
array_multi = array_uni.reshape(4,6)
array_multi

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

2. Modificamos el nuevo array `array_uni_02`

In [46]:
array_multi[3,4] = 978
array_multi

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21, 978,  23]])

Si hemos modificado `array_uni_02` y este fue resultado de una asignación a un array previo pero con dimensiones nuevas, podriamos esperar que `array_uni` no sufriera modificaciones. Vamos a verificarlo:
3. Verificamos contenido del array original `array_uni`

In [47]:
array_uni

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21, 978,  23]])

Como se observa, modificar un array tendrá como consecuencia modificar todas las dependencias que hayan surgido de él.Para terminar con esta sección veremos como podemos 'desenvolver el array de dos dimensiones para devolverlo a su estado original.

In [48]:
array_multi.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21, 978,  23])