# Introducción a NumPy

## ¿Qué es NumPy?

### Palabras Clave

* Paquete
* Matriz multidimensional
* Operaciones rápidas entre matrices
* Objeto ndarray
* Datos homogéneos
* Ejecución de código compilado.

Si nos dirigimos a la documentación oficial de [Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html), podemos decir, en resumen, que es una herramienta útil cuando deseamos realizar operaciones con matrices. Su potencial se muestra al trabajar con matrices de tamaños cada vez más grandes, ya que ejecuta código compilado para realizar las operaciones sin la necesidad de salir de Python.

Es importante destacar que los objetos ndarray deben ser de **datos homogéneos**, mencionándolo para evitar errores de ejecución.

## Diferencias entre el úso de NumPy y las secuencias estándar de Python

|Numpy|Python|
|:--------------------------------------:|:-------------------------:|
|Tamaño fijo en el momento de su creación|Pueden crecer dinámicamente|
|Los elementos deben ser homogéneos|Permite multples datos|
|Facilidad en operaciones matemáticas avanzadas y procesamiento de grandes conjuntos de datos|Requiere implementar las operaciones además de la reducción en el rendimiento|
|Compatibilidad con la mayoría del software científico/matemático basado en Python| **Saber cómo usar los tipos de secuencia integrados de Python es insuficiente**|

> Cambiar el tamaño de un *ndarray* creará una nueva matrz y eliminará el original.

> Es posible crear una matriz de objetos en NumPy permitiendo una mayor flexibilidad. Con la consecuencia de perder rendimiento y la capacidad de aprovechar las implementaciones más eficientes que ofrece el paquete.

> NumPy nos ofrece lo mejor de ambos mundos. Se ejecuta a velocidades cercanas a C, pero con la simplicidad del código que esperamos de algo basado en Python.

## ¿Por qué utilizar NumPy?

Pienso que la principal razón para utilizar NumPy es por su escalabilidad a paquetes basados en Python. Si deseamos utilizar Python como lenguaje de programación enfocado en aplicaciones cientificas de cualquier área NumPy es el estandar, tal es así que en la misma documentación refieren que la mayoria de las paqueterias que se implementan para Python requieren como base un arreglo de Numpy. El punto anterior es el fundamento de la necesidad de aprender a utilizarlo, como segundo punto esta el tiempo. Si nos enfocamos en el análisis de datos, encontraremos con frecuencia conjuntos de datos que superan el millon de datos, por ello es necesario tener una forma eficiente de preparar, procesar y analizar nuestros datos sin tener que sacrificar la facilidad en la codificación, esto es algo que logra el paquete Numpy gracias a las siguientes caracteristicas:

* Vectorización: Permite realizar operaciones en arreglos completos en lugar de iterar sobre elementos individualmente.
* Operaciones en C optimizadas: La implementación de las operaciones que realiza se implementan en C, provocando que se manipulen los datos a un nivel de abstracción más bajo.
* Radiodifusión: Permite realizar operaciones entre arreglos de diferentes formas y tamaños de manera automática y eficiente.

## ¿Cómo empezar a utilizar NumPy?

Lo primero que se debe hacer para utilizar NumPy es instalar la libreria utilizando:

```
pip install numpy

```
Después es necesario importar la biblioteca en nuestro script

In [1]:
# Importación de numpy con alias
import numpy as np

Si la estructura básica para utilizar NumPy es un array entonces debemos saber como crearlos o inicializarlos, antes de poder pensar en operarlos.

### Atributos básicos de la clase ndarray

- `ndarray.ndim`: El número de ejes (dimensiones) del array
- `ndarray.shape`: Es una tupla de números enteros que indica la longitud  de cada dimensión.*(filas, columnas)*
- `ndarray.size`: El número total de elementos del array, es igual a multiplicar los elementos de la tupla devuelta por `shape`.
- `ndarray.dtype`: Devuelve una descripción del tipo de elementos que existen dentro del array. NumPy proporciona algunos tipos adicionales, por ejemplo, `numpy.int32`, `numpy.int16` o `numpy.float64`.

### Creación de un array
#### Desde una lista de Python

In [2]:
lista_01 = [1, 2, 56, 878, 14, 45, 19, 21]
a = np.array(lista_01)
print(a)

[  1   2  56 878  14  45  19  21]


In [3]:
# Longitud de cada dimensión del array a
a.shape

(8,)

> **Nota** Observa que si el array es de una sola dimensión el atributo shape devuelve la tupla *(columnas,)* esta es una convención y lo que indica es que tenemos un array de *1 fila y 8 columnas*.

In [4]:
lista_02 = [[10,155,45],[21,178,75]]
b = np.array(lista_02)
b

array([[ 10, 155,  45],
       [ 21, 178,  75]])

In [5]:
# Longitud de cada dimensión del array b
b.shape

(2, 3)

Existen situaciones en donde necesitamos inicializar un array con valores que desconocemos y NumPy ofrece funciones para crear matrices con *contenido de marcador de posición inicial*.

#### Utilizando una función de NumPy

##### Matriz con ceros

In [6]:
c = np.zeros((5,3)) # Matriz de 5x3 rellena de zeros
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Número de dimensiones de la matriz
c.ndim

2

In [8]:
# Longitud de cada dimensión
c.shape

(5, 3)

In [9]:
# Número de elementos de la matriz
c.size

15

In [10]:
# Tipo de matriz
c.dtype

dtype('float64')

c es una matriz con:
- Dos ejes (**axis**) es decir, dos dimensiones (**rank**).
- Longitud de 5 filas y 3 columnas (**shape**)
- Un tamaño (**size**) de 15.
- Tipo de elemento `float64`

##### Matriz con unos

In [14]:
# Array cuyos valores son todos 1
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

##### Matriz cuyos valores son todos el valor especificado como segundo parámetro

In [15]:
np.full((2, 3, 4), 7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

##### Matriz generada con empty

El resultado no es predecible, rellena las dimensiones que se especifican con valores existentes en la memoria al momento de ejecución

In [24]:
np.empty((3,7,4))

array([[[6.95091521e-310, 6.95091521e-310, 0.00000000e+000,
         2.12199579e-314],
        [0.00000000e+000, 4.99006302e-322, 0.00000000e+000,
         0.00000000e+000],
        [2.12199579e-314, 4.24399158e-314, 2.12199587e-314,
         0.00000000e+000],
        [0.00000000e+000, 2.12199579e-314, 1.69759663e-313,
         4.94065646e-322],
        [0.00000000e+000, 0.00000000e+000, 2.12199579e-314,
         3.39519327e-313],
        [2.12199587e-314, 0.00000000e+000, 0.00000000e+000,
         2.12199579e-314],
        [3.60739284e-313, 2.12199588e-314, 0.00000000e+000,
         0.00000000e+000]],

       [[2.12199579e-314, 3.60739284e-313, 3.45845952e-322,
         0.00000000e+000],
        [0.00000000e+000, 2.12199579e-314, 3.60739284e-313,
         2.12199584e-314],
        [0.00000000e+000, 0.00000000e+000, 2.12199579e-314,
         3.60739284e-313],
        [4.10074486e-322, 0.00000000e+000, 0.00000000e+000,
         2.12199579e-314],
        [3.60739284e-313, 0.00000000e+000

#### Creación de array utilizando una función basada en rangos

##### Utilizando secuencias (arrange)
Cuando nos referimos a secuencias es definir un mínimo, un máximo y un salto entre cada valor sin incluir el valor máximo. `[mínimo, máximo)`

In [32]:
# (minimo, maximo, salto)
np.arange(1,10.5,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

##### Creando separaciones uniformes (linspace)
El siguiente código crea un array desde el 0.1 hasta el 1 con 10 elementos separados uniformemente.

A diferencia de la función anterior, con esta, podemos determinar el número de elementos que queremos que tenga nuestro array de forma más intuitiva.

In [30]:
# (minimo,maximo, número de elementos del array)
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### Creación de array con valores aleatorios (random.rand)
Esta función devuelve valores aleatorios entre 0 y 1

In [36]:
np.random.rand(7,3)

array([[0.97357766, 0.60334332, 0.00610339],
       [0.14525967, 0.83080975, 0.29123645],
       [0.26544999, 0.44229708, 0.22541964],
       [0.34453364, 0.6852017 , 0.03008661],
       [0.53101681, 0.46586342, 0.48793485],
       [0.77356659, 0.49323171, 0.27516396],
       [0.9581237 , 0.56273929, 0.55322243]])

#### Creación de array con valores aleatorios siguiendo una distribución normal (random.randn)


In [37]:
np.random.randn(7,4)

array([[ 0.06492108, -0.13549638, -4.15495084, -0.82519813],
       [-0.85354137,  1.13343628, -0.01695442, -0.96241243],
       [-0.30661349, -0.28342795, -0.14403835, -0.10030931],
       [-0.1960072 , -1.10633407, -0.94132525,  1.10133215],
       [-0.36855978, -0.95339559, -1.7253227 ,  1.11178091],
       [-0.45138403,  1.22943191,  0.18939349,  0.72516398],
       [-2.02122024,  1.84566928, -0.53496737,  0.56147894]])